### ISSUE TITLE
The model User is not registered

### ISSUE THREAD

**Issue by nikksbagul** [mapeveri/django-musette#67]
Hello,
I trying to use django-musette with my own custom Auth user model. It gives me following issue in creation of migrations.
`python manage.py makemigrations user_management

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/musette/admin.py", line 233, in <module>
    admin.site.unregister(User)
  File "/opt/myvirtual/py_3.5_dj_1.9/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model User is not registered`

Please give me any solution how can I use your package in my project.

**Comment by mapeveri** [comment]
@nikksbagul Hi, because use 'python manage.py makemigrations user_management'?. 

The migrations are for the application: 

                   python manage.py makemigrations musette 
                   python manage.py migrate musette.

**Comment by nikksbagul** [comment]
Still same issue occurred.

**Comment by mapeveri** [comment]
Ok. This feature still

**Comment by mapeveri** [comment]
Ok. This feature still

**Comment by mapeveri** [comment]
@nikksbagul I was confused this feature still is not supported. Can you give me a example of your custom user model?. I will add this feature.

**Comment by mapeveri** [comment]
@nikksbagul Can you try with this change?. If it works it, i will release the version.

Please, clone this repo and execute python setup.py install, and will installed the version 0.2.5.

Thanks!

**Comment by nikksbagul** [comment]
This is my custom auth user model.

```
class User(AbstractBaseUser):

    username = models.CharField(_('User Name'), max_length=64, unique=True, null=False, blank=False, db_index=True, db_column='username',)

    first_name = models.CharField(_('First Name'), max_length=40, null=False, blank=False)

    middle_name = models.CharField(_('Middle Name'), max_length=40)

    last_name = models.CharField(_('Last Name'), max_length=40)

    is_admin = models.BooleanField(_('Is Admin'), default=False)

    is_active = models.BooleanField(_('Is Active'), default=True)

    is_deleted = models.BooleanField(_('Is Deleted'), default=False)

    isstaff = models.BooleanField(_('Staff Status'), default=True)

    date_joined = models.DateField(_('Joined Date'), blank=True, null=True)
   
    change_password = models.CharField(_('Change Password'), max_length=1, null=False, blank=False, default='Y',)

    USERNAME_FIELD = 'username'

```
After update django-musette to 0.2.5 its give me issue in migrations 

> django.core.exceptions.FieldError:  Unknown field(s) (email) specified for User

**Comment by mapeveri** [comment]
You must add the field 'email', is required for the forum. The fields 'last_name', 'first_name', 'email' and 'username' are required.

**Comment by mapeveri** [comment]
I'm testing with your model, because I get the error: 

     raise NotRegistered('The model %s is not registered' % model.__name__)
     django.contrib.admin.sites.NotRegistered: The model User is not registered

You too?

**Comment by mapeveri** [comment]
I told you a few things, first of all, please, get the repo again with git clone and install it.

For the forum I recommend using AbtractUser instead of AbstractBaserUser, because there are many fields of the user model that the forum uses.

Check this: https://github.com/mapeveri/django-musette/blob/master/example/main/models.py#L10

With that it works, but there is a small problem. The fields that one adds to the new user model are not seen in the django admin, because I am using 'UserAdmin' in the code.

Check: https://github.com/mapeveri/django-musette/blob/master/musette/admin.py#L223

I'm going to look for a way so the user can customize this.

**Comment by mapeveri** [comment]
Ready, check this: https://github.com/mapeveri/django-musette/blob/master/docs/custom-user-model.rst

That has to work. If it is ok, I release the version.

**Comment by mapeveri** [comment]
Release version 0.2.5 with this issue and more. Upgrade with pip.
